name: SeeleServerAssist
version: '${project.version}'
main: net.mc42290.seeleserverassist.SeeleServerAssist
api-version: 1.19

commands:
  mc42290:
    usage: /mc42290 ...
  mc42290.job:
    usage: /mc42290.job ...